from .peak_detection_amp_threshold import peak_detection_amp_threshold
from .peak_detection_local_search import peak_detection_local_search
from .peak_detection_matched_filter_robust import peak_detection_matched_filter_robust
from .peak_detection_modified_pan_tompkins import peak_detection_modified_pan_tompkins
from .peak_detection_pan_tompkins import peak_detection_pan_tompkins
from .peak_detection_simple import peak_detection_simple
