from .peak_det_amp_threshold import peak_det_amp_threshold
from .peak_det_local_search import peak_det_local_search
from .peak_det_matched_filter_robust import peak_det_matched_filter_robust
from .peak_det_modified_pan_tompkins import peak_det_modified_pan_tompkins
from .peak_det_pan_tompkins import peak_det_pan_tompkins
from .peak_det_simple import peak_det_simple
from .peak_det_adaptive_hr import peak_det_adaptive_hr
